### ISSUE TITLE
Possible AI CPUE discrepancy 

### ISSUE THREAD

**Issue by EmilyMarkowitz-NOAA** [afsc-gap-products/gapindex#14]
> Copying from an email @Ned-Laman-NOAA sent me regarding a discrepancy in the station-level CPUE estimates in the AI estimates and in FOSS, that this package may also likely encounter. My resolve on the FOSS side was to disregard, but I am interested to know how the R package will want to address it. 

There are 15 [station-level cpue] records in the AI record that could be problematic. [Upon recalculating the station-level cpue estimates,] It seems odd that the vast majority of records [in the current ai cpue oracle tables] comply with our expectations and just a few don't. There is a chance that for these older records, `RACEBASE` has been revised (e.g., unid'd sculpins (21300) might've been broken out into species ids) and CPUE/Biomass weren't re-run for that cruise. Re-running older biomass estimates is problematic for a few reasons that I'm happy to chat about, but I have a sneaking suspicion that this may be part of the discrepancy.

Here's the SQL Plus I was using to address the question:
```
select a.vessel,a.cruise,a.haul,a.species_code,a.wgtcpue,b."cpue_kgkm2",
a.wgtcpue-b."cpue_kgkm2" diff, round(100*(abs(a.wgtcpue-b."cpue_kgkm2")/a.wgtcpue),1) pct_diff
from ai.cpue a, racebase_foss.racebase_public_foss b
where a.hauljoin = b."hauljoin"
and a.species_code = b."species_code"
and a.wgtcpue != 0
order by -(abs(a.wgtcpue-b."cpue_kgkm2"))
```

**Comment by EmilyMarkowitz-NOAA** [comment]
@Ned-Laman-NOAA is this still an issue we are concerned about? Especially with all of the work that @zoyafuso-NOAA et al. have done on the design based indices R package? I'm guessing possibly not, in which case I'll close the issue :)

**Comment by Ned-Laman-NOAA** [comment]
A couple of things. 
I suspect these discrepancies still exist between RACEBASE and AI.CPUE but was not able to prove it since the code I was using before no longer "sees" RACEBASE_FOSS.RACEBASE_PUBLIC_FOSS for some reason.
As we move to a model where we produce CPUE for every taxon (i.e., RACE Species Code) and do so independently of the AI and GOA CPUE tables, then this problem should go away (I hope).
We should have a broader discussion (including @Duane-Stevenson-NOAA) about timing and implementation of this change. This ties together with the new table structures we're developing and all of that and it's been a while since we've looped Duane back in so let's think about making that happen.

**Comment by zoyafuso-NOAA** [comment]
The disconnect between any modification in RACEBASE.CATCH and the CPUE tables in the GOA and AI schemata are noted in the [data changes brief](https://docs.google.com/document/d/1ie0it6G_V_PrpO1fYe-731Fvubuahn2yi0ixBIpaYO8/edit#) as one of the main sources of mismatch between the existing Oracle tables and the output from gapindex. 

I agree with @Ned-Laman-NOAA 's point about making sure we really get down the timing of when we rerun gapindex for production. Nancy is also a part of this workflow as she seems to be our liaison with age and growth about when new age data come in. 

I'll close this issue for now.
