### ISSUE TITLE
AI-GOA Age Data Upload Schedule

### ISSUE THREAD

**Issue by zoyafuso-NOAA** [afsc-gap-products/gapindex#23]
Hi Nancy (Ned cc'd),

Thanks for posting the EBS/NBS age data updates to the modsquad discussion board last week. That will be super helpful in the future. 

I'm in the process of comparing the age compositions that come out of the gapindex package with those from AGECOMP_TOTAL tables in the AI and GOA schemata. I'm getting mismatches with the AGECOMP_TOTAL tables and the agecomps that come out of gapindex so I'm investigating any possible reasons for this. I'm reminded of [this issue](https://github.com/afsc-gap-products/data-requests/issues/8#issue-1141917005) from the gap requests repo but I think this is a separate issue. 

Here's the question: In the AI-GOA, when age data are uploaded for a particular species/year, are they all uploaded all at the same time? Conversely are there cases where only a portion of the age data for a species/year are uploaded and then some time in the future (years later), the other portion of the age data for that species/year are uploaded. I'm asking this because if this is occurring and we don't redo agecomp calculations for all years, then those added years data aren't integrated in the historical agecomps over time, which could explain those mismatches. 

Thanks,
Zack

**Comment by Ned-Laman-NOAA** [comment]
I think what you're asking is if we ever update agecomps from an incomplete set of age data, receive more data later, and then update only the agecomps for the second portion (not recalculating agecomp for the whole species).
If that's right, then I probably don't know the answer. I haven't been responsible for producing the agecomps long enough to have a wide range of experience with the incoming data. The ones I've run so far have been from a single data set provided by age and growth and there haven't been subsequent updates to ages. We're literally talking about updates run in the last 12 months or so though so I can't comment on what's gone before. Having looked at the agecomp code I inherited (G:\GOA\R\agecomp\agecomp.Rproj) it looks like it's set up to run by default on all years where there are ages in RACEBase.SPECIMEN one species at a time. There is an option to single out a year, but this is not the default action.

**Comment by zoyafuso-NOAA** [comment]
I'm thinking of a scenario where we get, say, half of the age dataset for a year/species, run the agecomp script, and upload a version of the agecomps to Oracle. Then later, the rest of a year/species otoliths are aged, we get the other half of the age dataset, recalculate the agecomps on the now full age dataset, and then overwrite the agecomps that were on Oracle with the updated agecomps.

The questions are: 1) Does the first part of the scenario occur? 2) Or is the agecomp script run only when all the otoliths for a species/year are read and the AGE column is updated in RACEBASE.SPECIMEN? 3) If the first part of the scenario occurs, does the second part of the scenario occur? 

Similar to when records in RACEBASE.CATCH/RACEBASE.HAUL are updated over time and those changes don't get propagated to the AI./GOA.CPUE tables, I'm wondering whether it's the same issue if/when the AGE records in RACEBASE.SPECIMEN are updated after the agecomp scripts are run and those updates are not propagated to the AGECOMP tables. That would cause an easy mismatch when comparing with the agecomps to those coming from gapindex.

**Comment by Ned-Laman-NOAA** [comment]
Playing a little bit of tag here, but @NancyRoberson is involved with the intake of age data from the age and growth crew more so than me so I'm thinking she can better respond to than I to whether we ever get a partial set of ages for a species/cruise and then more ages for the same species/cruise later. 
My gut reaction is that I don't think that happens because it just doesn't seem like a good practice, but I have no basis for saying that.
The situation where there is a lack of synchrony between the data tables and the product tables (e.g., catch/haul & cpue/biomass) could happen with agecomps too. If changes are made to ages in the Specimen table, there isn't a trigger (other than human intervention) that would invoke recalculating agecomps.

**Comment by NancyRoberson** [comment]
Hi Zach and Ned,
I apologize for the late response - I was waiting to hear back from Jon Short (A&G Lab) to confirm my answer or give additional information.   But here is what I have seen over the years:

Most of the time, the ages for one species/year are loaded at the same time. This is especially if they were small age set or were collected on just one vessel.

 Sometimes, especially the larger data sets (e.g. pollock, cod, ATF),  the ages are loaded for one vessel before the other and the time period between the two loadings is _usually_ less than 6 months.  E.g. March and August.  

Occasionally, there is a special case scenario when a stock assessment author requests to have more otoliths read from a past year - e.g. you may see 2007 otoliths that are loaded in 2015, or there is a lag time by several years due to a back log of otoliths that the A&G Lab is catching up on.

The spreadsheets below are the GOA and AI otoliths that have been loaded to RACE_DATA.  They include the cruises, species, vessels and when the age sets were loaded.  I have highlighted in tan the cruise/species that had different load dates.

I hope that makes sense.  Let me know if you need more informations :)


[GOA_ALL SPECIES_Specimen Age Sets.xlsx](https://github.com/afsc-gap-products/gapindex/files/11454093/GOA_ALL.SPECIES_Specimen.Age.Sets.xlsx)

[AI_ALL SPECIES_Specimen Age Sets.xlsx](https://github.com/afsc-gap-products/gapindex/files/11454091/AI_ALL.SPECIES_Specimen.Age.Sets.xlsx)

**Comment by zoyafuso-NOAA** [comment]
Thank you Ned and Nancy. These will be useful on my journey of finishing table output checking (so close now!). I'll close this issue.
