### ISSUE TITLE
data access

### ISSUE THREAD

**Issue by BenWilliams-NOAA** [afsc-gap-products/gapindex#50]
https://github.com/afsc-gap-products/gapindex/blob/8c1c66dbc32504407bb5e7c03cfce3453973bd52/R/get_connected.R#L51

Getting this message:

Error in gapindex::get_connected(db = "afsc") : 
  Cannot connect to these tables in Oracle:
RACE_DATA.CRUISES
RACE_DATA.SURVEYS
RACE_DATA.SURVEY_DEFINITIONS
RACE_DATA.VESSELS

Please contact afsc.gap.metadata@noaa.gov for access to these tables and then try connecting again.

And the email get's bounced back. Also guessing that many assessment authors would get this message if they use this package?

**Comment by zoyafuso-NOAA** [comment]
Hi @BenWilliams-NOAA 

Thanks for unknowingly being our first test subject on the new get_connected() function. We put this error into the function because there were some folks who were trying the package who couldn't access the RACE_DATA schema and we're looking at ways to update folks' access privileges so avoid this issue in the first place. 

Pinging @EmilyMarkowitz-NOAA on whether there is a better email address. In the meantime, @ChrisAnderson-NOAA , can you grant Ben access to those tables in RACE_DATA please?

**Comment by EmilyMarkowitz-NOAA** [comment]
Thanks for pinging me, @zoyafuso-NOAA! @BenWilliams-NOAA: what kind of bounce-back message were you getting from [afsc.gap.metadata@noaa.gov](mailto:afsc.gap.metadata@noaa.gov)? I'll put in a ticket to OFIS to get that back online. Otherwise that's what I would have told you to contact, and if not that, I would have also directed you to @ChrisAnderson-NOAA.

**Comment by BenWilliams-NOAA** [comment]
Hey Em the message was:


Address not found
--
Your message wasn't delivered to afsc.gap.metadata@noaa.gov because the address couldn't be found, or is unable to receive mail.

**Comment by EmilyMarkowitz-NOAA** [comment]
Great, thanks! Sending in a ticket of OFIS now.

**Comment by EmilyMarkowitz-NOAA** [comment]
Well... I'm the problem. It's me. Please use nmfs.afsc.gap.metadata@noaa.gov instead. I've already gone through all of the repos/web pages I can find and changed out the address.  I must have mistakenly copied and shared it out. Thanks @BenWilliams-NOAA for bringing this to our attention!

**Comment by zoyafuso-NOAA** [comment]
thanks!
