### ISSUE TITLE
gap_products not matching gapindex for agecomp

### ISSUE THREAD

**Issue by pete-hulson** [afsc-gap-products/gapindex#58]
### Issue

Hey there,

I'll do my best here to make this long story short... I've been playing around in gapindex to make sure what we're doing in [https://github.com/BenWilliams-NOAA/surveyISS](url) to come up with age&length comp input sample size matches with what you guys are producing (in a nutshell what this means is making sure that the underlying comps without resampling match exactly with what you give us). First off - well done my friends, well done with where you've taken that old stuff to gapindex. 

K, so here's the issue I've stumbled across. In the process of all this I've been doing a bunch of error checking to ensure surveyISS is matching what gapindex produces and what is up on gap_products. Basically, what I've stumbled across is that it looks like what gapindex produces and what's up in gap_products.akfin_agecomp doesn't match (but, gapindex and gap_products match exactly for gap_products.akfin_sizecomp). I'm at a loss as to why that would be...

I've copied in below the script I put together to do this checking that you should be able to run as well - it's silly that github won't let you attach R files. To make it a reasonable run length I've subsetted to GOA and to arrowtooth, pcod, pollock, and POP - from these tho the issue should reveal itself. I'm really hoping you find something dumb I've done and you just call me an idiot and we all move on...

Pete
```
# script to test match between gapindex and gap_products

# load/source libraries/functions
library(tidyverse)
library(tidytable)
library(gapindex)
library(afscdata)
library(DBI)

# species/region/year to test
species_test = c(10110, 21720, 21740, 30060)
region = 'goa'
yrs = 1990
survey = 47
stratum = 99903

# compute using gapindex ----

# get data
gapdata <- gapindex::get_data(year_set = seq(yrs, 2025),
                              survey_set = toupper(region),
                              spp_codes = species_test,
                              pull_lengths = TRUE)

# get cpue
cpue <- gapindex::calc_cpue(gapdata)

# get stratum pop'n
racebase_stratum_popn <- gapindex::calc_biomass_stratum(gapdata,
                                                        cpue)

# get stratum pop'n at length
gap_lc <- gapindex::calc_sizecomp_stratum(gapdata,
                                          cpue,
                                          racebase_stratum_popn) 

# get age-length key
alk <- gapindex::calc_alk(gapdata,
                          unsex = "all")

# get stratum-level age pop'n
gap_age_comp_st <- gapindex::calc_agecomp_stratum(gapdata,
                                                  alk,
                                                  gap_lc)

# get regional level age pop'n
gap_ac <- gapindex::calc_agecomp_region(gapdata,
                                        gap_age_comp_st)

# rename and sum over strata
gap_lc %>% 
  dplyr::rename_all(tolower) %>% 
  tidytable::summarise(abund_gapindex = sum(population_count), .by = c(year, species_code, sex, length_mm)) %>% 
  tidytable::rename(length = 'length_mm') -> gapindx_sizecomp
  
gap_ac %>% 
  dplyr::rename_all(tolower) %>% 
  tidytable::summarise(agepop_gapindex = sum(population_count), .by = c(year, species_code, sex, age)) -> gapindx_agecomp


# get data from gap_products on akfin ----

# get connected to akfin
db = 'akfin'
conn = afscdata::connect(db)

# pull akfin_sizecomp table
dplyr::tbl(conn, dplyr::sql('gap_products.akfin_sizecomp')) %>% 
  dplyr::rename_all(tolower) %>% 
  dplyr::filter(survey_definition_id %in% survey,
                species_code %in% species_test,
                year >= yrs,
                area_id == stratum) %>% 
  dplyr::select(year, species_code, sex, length = length_mm, abund_gapprod = population_count) %>% 
  collect() -> gapprod_sizecomp

# pull akfin_agecomp table
dplyr::tbl(conn, dplyr::sql('gap_products.akfin_agecomp')) %>% 
  dplyr::rename_all(tolower) %>% 
  dplyr::filter(survey_definition_id %in% survey,
                species_code %in% species_test,
                year >= yrs,
                area_id == stratum) %>% 
  dplyr::select(year, species_code, sex, age, agepop_gapprod = population_count) %>% 
  collect() -> gapprod_agecomp


# make comparisons ----

# sizecomp test

# gapindex to gap_products on akfin
gapindx_sizecomp %>% 
  tidytable::left_join(gapprod_sizecomp) %>% 
  tidytable::mutate(diff = abund_gapindex - abund_gapprod) %>% 
  # print(n = 250)
  tidytable::summarise(test = sum(diff, na.rm = TRUE), .by = species_code)
# note: length exactly matches, 
#   but, some years in gapindex but not in gap_products, like 1990 for arrowtooth 


# agecomp test

# gapindex to gap_products on akfin
gapindx_agecomp %>% 
  tidytable::left_join(gapprod_agecomp) %>% 
  tidytable::mutate(diff = agepop_gapindex - agepop_gapprod) %>% 
  # print(n = 250)
  tidytable::summarise(test = sum(diff, na.rm = TRUE), .by = species_code)
# note: does not match - some years in gapindex but not gap_products, some ages in gapindex but not gap_products
```

**Comment by zoyafuso-NOAA** [comment]
Hi Pete, 

Thanks for posting this. The difference is in how the age-length key is calculated. The default in the function is to globally-fill missing values in the alk but the way the legacy agecomps were calculated, missing values are not filled in. Try adding a  `global = F` argument to the gapindex::calc_alk function call. You will also see that since the last time the akfin tables were updated, new POP 2023 otolith data were added to RACEBASE (yay). Let me know how that goes. 

Z

**Comment by zoyafuso-NOAA** [comment]
In addition, ATF in 1990 was omitted from GAP_PRODUCTS because it was before we in GAP had confidence that ATF (and Kamchatka flounder) was being confidently identified (I think the cutoff was 1991 or 1992). This is a new component for GAP and we were unsure about how it would affect folks' stock assessment data pulls because we were not clear on how assessors were treating ATF data in the early 90s. However, I imagine since we don't get too many Kamchatka flounder in the GOA, it would be safe to assume that the ATF reported in the GOA in 1990 were all ATF?

**Comment by pete-hulson** [comment]
Hey Zack,

Quick point of clarification, I'm not comparing with legacy values here. What this comparison is doing is comparing between what is computed using gapindex, and what is posted up on AKFIN in the gap_products.akfin_agecomp table. Basically, the issue is that I can't reproduce what's in gap_products using gapindex - and I just tried the global = F argument with the same result (I've also tried unsex = "unsex" rather than "all" in gapindex::calc_alk and it still doesn't match gap_products). Pasting the script into the issue got all funky, so the script is here: https://github.com/BenWilliams-NOAA/surveyISS/blob/main/dev/gap_check/dev/gap_prod_indx_test.R, please run and let me know if you get the same result.

I'm not as concerned with matching legacy values precisely - I'm on board with the changes you guys have made and I'm in support. That said, I think there's potentially some more conversation to be had about using a global ALK. I can see the arguements for, but if growth is changing over time I'm unsure how that would play into that, you could potentially be putting lengths from the length pop'n into the wrong age classes...

As far as the ATF issue - maybe talk with Kalei 'bout that? It was just the only mismatch between gapindex and gap_products that I saw for the akfin_sizecomp table.

Thanks man,

Pete

**Comment by zoyafuso-NOAA** [comment]
Yeah, I still get good matches when I use global = F and unsex = 'all' into the calc_alk function. I am using gapindex version 2.2.0. Is that you're using? 

The standard for agecomp production is to use global = F in the alk calculation, and the alk is year/sex specific for a given species, which address any changes in growth rates over time. The global = T option is currently only used when preparing data for ModSquad VAST age comp runs, and when the option is turned on, missing alks values are filled in only using the year that the value comes from, which also address year- and sex-specific growth.

**Comment by pete-hulson** [comment]
I'm also using 2.2.0. Couple of questions:

1. Just to be clear - you're comparing between gapindex and what's currently on AKFIN in gap_products?
2. Have you run the script that I shared with you? And, if so, are you getting matches?
3. If not on (2), could you share the script you're running?

Trying a different approach, attached are (1) what is being produced by gapindex with global = F and unsex = "all" in gapindex_agecomp.csv, and (2) what I'm pulling from AKFIN that's in gap_products.akfin_agecomp in gapprod_agecomp.csv. The column names a different than what you guys are using, but I think it should be pretty self-explanatory.

Good to know on how the global ALK is being used. On that note, if you have missing alk values, doesn't it mean that you don't have obs for that year and you then fill it with the global alk across all years? That's at least what it look like the code is doing.

Gotta love the mutliple conversation threads in a single issue... But, thanks for working with me on this Zack

[gapindx_agecomp.csv](https://github.com/afsc-gap-products/gap_products/files/15278647/gapindx_agecomp.csv)
[gapprod_agecomp.csv](https://github.com/afsc-gap-products/gap_products/files/15278648/gapprod_agecomp.csv)

**Comment by zoyafuso-NOAA** [comment]
Hi Pete,

Yes, I am comparing what comes out of gapindex to what is on AKFIN_AGECOMP. I ran the script you linked, but I forgot that I had changed the end date of the data pull to 2023 instead of 2025 when I first responded. When I changed it back to 2025 I was able to recreate the mismatches you attached but when I set to 2023, they were able to match well. Now I don’t know why this happens and will investigate that further. 

I would suggest having that end date be 2023 instead of 2025 for your comparisons and check whether that resolves many of the mismatches. The mock 2025 were arbitrarily created from 2019 data and not using gapindex::get_data() with 2025 in the year_set argument.

Global = F and unsex = “all” should still be the arguments in the calc_alk function.

**Comment by pete-hulson** [comment]
Thanks Zack,

I don't think 2025 has anything to do with it, you guys were definitely ahead of the game to have all the strata ids change with the 2025 restratification. The mismatches I was finding were occuring throughout the time series (you can see that if summarizing across species_code and years, rather than just species_code in the script I sent) - I was ignoring the most recent years when looking at that (cause some, like POP, don't have 2023 survey ages in the database yet).

All in all, I get good matches now too. It looks like you updated the gap_prodcuts.akfin_sizecomp and akfin_agecomp on friday - were there some issues with the old tables not matching with gapindex?

Also looks like the rounding when summing population_count in the agecomp calcs was done at regional level in the akfin tables you updated rather than the strata level (when summed across lengths), which makes more sense to me, and makes the code much more efficient (if you're calculating the population_count for agecomps with the ALK at the regional level rather than strata).

**Comment by zoyafuso-NOAA** [comment]
Oh god, okay so it's good now? The mismatches I was seeing was also throughout the time series.

I see now the AKFIN_LOAD_DATE on AKFIN's version of GAP_PRODUCTS.AGECOMP is dated May 10th. The previous version must have been a really old version in which I mistakenly specified the wrong arguments when calculating the GOA size and age comps.  

There's often a lag that I'm still figuring out between when I create all the indices in gapindex -> uploading to AFSC's version of GAP_PRODUCTS --> those tables being transferred to AKFIN --> those products being hosted on AKFIN's version of GAP_PRODUCTS. So I apologize if the actual issue was comparing gapindex to an old version of GAP_PRODUCTS.

**Comment by pete-hulson** [comment]
Sounds good man - I think that was the issue (comparing to an old version in which something was amis), but really glad that we're matching up with what's going on here. Thanks again for all the help Zack, and really apreciate you being so responsive.
