### ISSUE TITLE
Questions for Ned/Wayne about size/age comp code

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [afsc-gap-products/gapindex#9]
## Questions  - edited to reflect answers
1. What does -9 mean in the age comps table? It shows up in `GOA.AGECOMP_TOTAL` as an age class
      **A: Length but no age.**
2. Where does `AGEPOP` come from in `GOA.AGECOMP_TOTAL` ? 
From Maia: 
> A colleague indicated that  AGEPOP is the sum (in weight?) of trawl catches for that year/age/sex. Here's the query in the original script I have:
> 
>  MyQuery<-paste0("SELECT GOA.AGECOMP_TOTAL.SURVEY,\n ",
>                 "GOA.AGECOMP_TOTAL.SURVEY_YEAR,\n ",
>                 "GOA.AGECOMP_TOTAL.SPECIES_CODE,\n ",
>                 "GOA.AGECOMP_TOTAL.AGE,\n ",
>                 "GOA.AGECOMP_TOTAL.SEX,\n ",
>                 "GOA.AGECOMP_TOTAL.AGEPOP\n",
>                 "FROM GOA.AGECOMP_TOTAL\n ",
>                 "WHERE GOA.AGECOMP_TOTAL.SURVEY     =" 'GOA' \n ",
>                 "AND GOA.AGECOMP_TOTAL.SPECIES_CODE = 10130")
> 
> ... Is  AGEPOP  something I can straightforwardly calculate on my own from the  RACEBASE.SPECIMEN data, and/or are there plans to update the GOA.AGECOMP_TOTAL table to include the latest age data?

3. For the workflow of generating age comps, if Peter/Michael ran the `a.agecomp.R` script in R every year or 2x/year, did they loop through all the species and replace the table entirely? Or just replace a specific year/species combo? The answer to this may be in the SQL code within Peter's script.

**Comment by MargaretSiple-NOAA** [comment]
Just a note: I think `AGEPOP` is a sum of the numbers at age based on [this line](https://github.com/afsc-gap-products/design-based-indices/blob/0d431875e30fec2abdec64fc0143dcd587530318/R/get_age_comps_mm.R#L246) (and following) in the cod script.

**Comment by Lewis-Barnett-NOAA** [comment]
1) -9 indicates no age, I believe (some flavor of unable to age/unreliable age)
2) no idea, that one is for Wayne or @Ned-Laman-NOAA

**Comment by Ned-Laman-NOAA** [comment]
Agreed about -9...basically has a length but no age

There is an R script (A.agecomp) that generates those numbers. The script needs some work and modernization, but it is presently the standard.

**Comment by MargaretSiple-NOAA** [comment]
> There is an R script (A.agecomp) that generates those numbers. The script needs some work and modernization, but it is presently the standard.

@Ned-Laman-NOAA is this the one you're thinking of ?
![image](https://user-images.githubusercontent.com/73858992/167052379-036b9299-fee1-44ee-9c18-3932c0413f2c.png)

This is what I'm using to compare to the RACEBASE `AGECOMP_TOTAL ` ... I think I'm on the right track but just want to be extra sure. The csv I sent you has a comparison between the outputs from that R script and the RACEBASE table.

**Comment by Ned-Laman-NOAA** [comment]
I think that the script you've highlighted is derived from the A.agecomp script stored in the .Rdata workspace in that same folder. I further think that A.agecomp is the script we would run for each and every species, but the A.cod.agecomp.split.a.species would be some special request for cod. That said, I'm still hesitant to run the A.agecomp and replace the GOA.AGECOMP_TOTAL table object until I have more time to ensure that I'm making the right moves.

**Comment by MargaretSiple-NOAA** [comment]
Oh, a sneaky .RData script in hiding!!! Thank you for bringing my attention to that! I will check `A.agecomp()` in that work space.

**Comment by Ned-Laman-NOAA** [comment]
That Text.backup folder should also have copies of all or most of the scripts stored in .Rdata.  
I'm going to give Wayne a call shortly to talk to him about the agecomp stuff and I'll put what I learn in this thread.
Final thought: our old school way of making projects and storing code followed this model of creating an .Rdata workspace and storing the active code in there and the working code in text files outside. That might help you find other stuff when you are cruising around on the G-drive for code!

**Comment by Ned-Laman-NOAA** [comment]
AgeComp - more useful information
agecomp relies on sizecomp which relies on biomass estimates (i.e., have to update biomass, then sizecomp, before running agecomp IF anything has changed with biomass since the last time it was run)
The historic SQL scripts for running biomass, sizecomp, and agecomp are here (G:\GOA\biomass_sizecomp_scripts)
There are instruction for running sizecomp and agecomp in their respective folders here (G:\GOA\R\sizecomp OR agecomp)
Wayne was running an bi-annual maintenance cycle where he would update agecomp in late Spring ahead of the summer stock assessment season and then would run it again in September.
The agecomp (and presumably sizecomp too) model is presently to rename the existing AGECOMP_TOTAL table in Oracle and replace it entirely with a new run of A.agecomp.R 
This model should probably be revised to append data to an existing table with tests and prompts to overwrite existing data, but that's just me typing out loud!

**Comment by MargaretSiple-NOAA** [comment]
Awesome. I will look at all those functions in the .Rdata workspace but if you could ask him what his workflow was for generating `GOA.AGECOMP_TOTAL` (especially if it involves a SQL script I don't have yet!) I would be very grateful.

**Comment by MargaretSiple-NOAA** [comment]
Added a comparison table [here ](https://docs.google.com/spreadsheets/d/12semncRuVTtNWsgzComXDicOyqPjD33YVDvaq3G32r4/edit?usp=sharing) showing differences between the tables generated by the `A.agecomp()` code and the `GOA.AGECOMP_TOTAL` table in Oracle. The "does it match" column indicates an exact match between the two tables.

**Comment by Ned-Laman-NOAA** [comment]
Kind of scary, but here's what I had to do to get Maia's FHS age comps into GOA.AGECOMP_TOTAL using the A.agecomp script. I switched Peter's stored uid and pwd to the GOA schema access. I had to update the code at the end of the script to pick up "goa.db" as the RODBC channel instead of "channel", I had to comment out all of the open browsers Peter had left in there, and I updated the sql query at line 317 to the an "insert into agecomp_total" instead of a "create agecomp_total as" query. I then ran the script 2x: 1 for FHS in 2017 and one for FHS in 2019 informed by the fact that until I ran those the max year for FHS in GOA.AGECOMP_TOTAL was 2015. I saved none of these fixes to the A.agecomp script since now I'm not convinced this is the main code they were running for agecomps before, given it's inability to successfully complete without those edits to the RODBC channel code. Since Megsie was able to show that the math was reproducible in A.agecomp I'm confident I put the right numbers into GOA.AGECOMP_TOTAL, but it remains an open question which of the scripts in this project was the extant script for doing this as part of a process rather than the one off I did for Maia's data request. We need to investigate more fully which script is The One to Run for agecomps before the end of summer 2022. Also note that having waded through Wayne's Data Movies that he made and shared, he did not do a move for running agecomp, only for running biomass and sizecomp from the old SQL scripts.

**Comment by Ned-Laman-NOAA** [comment]
One more thought. We need to do an inventory of agecomp_total rel to what we have ages for in racebase.specimen to see what could be updated in the former but hasn't been. This looks to me like the maintenance has been spotty and non-systematic. I would like to establish some sort of go/no go communication from age & growth to us about whether or not be we can/should run agecomp with the ages we have or should be waiting until they tell us a species/year is complete and ready. I think Nancy needs to be part of this conversation as well.

**Comment by MargaretSiple-NOAA** [comment]
Ooh, I didn't know this section about creating the table:

> updated the sql query at line 317 to the an "insert into agecomp_total" instead of a "create agecomp_total as" query

Good to know! I made many of these changes to agecomps_a too. So yes, I think we should come up with a robust workflow for generating those tables and pushing them up to Oracle. To me, it makes sense to have two paths: 
1) a 'quick update' to make a table for, e.g., sensitivity analysis (I think this is what Maia is doing) and 
2) a scheduled, heavily reviewed process by which we run the script to generate the tables for Oracle. 

Agree that this second process is a trickier one because it's not super clear how long we should wait before publishing those tables. It doesn't seem to make sense to wait until all the otoliths for a given year are aged, but we also don't want to be too hasty and push something that is incomplete/doesn't make sense. 

I think we should probably meet in August to discuss this stuff, as Ned is leaving soon for the survey!

**Comment by MargaretSiple-NOAA** [comment]
I can work on this part. I may recruit Lewis and others to help.

> One more thought. We need to do an inventory of agecomp_total rel to what we have ages for in racebase.specimen to see what could be updated in the former but hasn't been. This looks to me like the maintenance has been spotty and non-systematic. I would like to establish some sort of go/no go communication from age & growth to us about whether or not be we can/should run agecomp with the ages we have or should be waiting until they tell us a species/year is complete and ready. I think Nancy needs to be part of this conversation as well.

**Comment by Ned-Laman-NOAA** [comment]
Fast forward to February 2023 and we now live in a world where Zack's gapindex is generating biomass, sizecomp, and agecomps and it seems like most of the questions in this thread were either answered or are now moot because the design-based values are being generated elsewhere than from the old A.agecomp() code. I'm tagging in Em and Zack to this thread since the former has been tracking all of these issues as they relate to GAP_PRODUCTS and the latter may be able to tell us if there are outstanding questions remaining about the issues in this thread.

**Comment by MargaretSiple-NOAA** [comment]
Yep! This is a really old one. I am actually not sure of the status of the age comps for some of the trickier stocks, so I will leave it to Zack to close this issue if it doesn't apply anymore. I suspect it doesn't.

**Comment by zoyafuso-NOAA** [comment]
This is correct, Ned. This issue really helped figure out how to script the agecomp calcs in gapindex so I'm grateful that Megsie brought it up.
